#!/usr/bin/env python3
"""Build the static, crawler-readable HRD product from normalized datasets."""
from __future__ import annotations

import csv, hashlib, html, json, re, shutil
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
BASE = "https://healthresearchdatabase.com"
ACTIVE = {"RECRUITING", "NOT_YET_RECRUITING", "ACTIVE_NOT_RECRUITING", "ENROLLING_BY_INVITATION"}
DESIGNS = {"a":"Systematic review / meta-analysis","b":"Randomized controlled trial","c":"Controlled / clinical trial","d":"Observational research","e":"Other research"}

def load(name, default):
    p=DATA/name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else default

def esc(v): return html.escape(str(v or ""), quote=True)
def slug_label(v): return str(v or "").replace("_"," ").title()
def write(rel, text):
    p=ROOT/rel; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding="utf-8")
def dump(rel, value): write(rel,json.dumps(value,indent=2,ensure_ascii=False)+"\n")
def blob(rec):
    return " ".join(str(x or "") for x in [rec.get("title"),rec.get("journal"),*(rec.get("mesh") or []),*(rec.get("keywords") or []),*(rec.get("conditions") or []),*(x.get("name","") for x in rec.get("interventions",[]) or [])]).lower()
def match(rec, terms): return any(t.lower() in blob(rec) for t in terms)
def clean_and_classify_legacy(studies):
    """Remove obvious non-human false positives and improve legacy title-only design labels.

    The live updater has abstract-aware classification; this also upgrades the bundled snapshot.
    """
    animal=re.compile(r"\b(beef cattle|bovine|porcine|swine|murine|mice|mouse|rats?|canine|dogs?|equine|horses?)\b",re.I)
    cleaned=[]
    rules=[
      ("a","Systematic review / meta-analysis",r"\b(systematic review|meta-analysis|meta analysis|scoping review)\b",.84),
      ("b","Randomized controlled trial",r"\b(randomi[sz]ed|double[- ]blind|single[- ]blind|sham[- ]controlled|crossover trial)\b",.80),
      ("c","Controlled / clinical trial",r"\b(clinical trial|controlled trial|intervention study|pilot trial)\b",.70),
      ("d","Observational research",r"\b(prospective cohort|retrospective|cross-sectional|observational|case-control|cohort study)\b",.76),
    ]
    for s in studies:
        if animal.search(s.get("title", "")): continue
        if s.get("design_class")=="e":
            for code,label,pattern,confidence in rules:
                if re.search(pattern,s.get("title", ""),re.I):
                    s["design_class"]=code; s["design_label"]=label; s["classification_source"]="Title methods heuristic"; s["classifier_confidence"]=confidence; break
        cleaned.append(s)
    return cleaned
def stat_date(stats):
    raw=stats.get("generated_at")
    try: return datetime.fromisoformat(raw.replace("Z","+00:00")).strftime("%B %-d, %Y at %H:%M UTC")
    except Exception: return "pending first refresh"
def iso_date(stats):
    raw=stats.get("generated_at")
    return raw[:10] if raw else datetime.now(timezone.utc).strftime("%Y-%m-%d")

def logo():
    return '<span class="logo-mark" aria-hidden="true">HR<span>↗</span></span><span class="logo-type">Health Research Database<small>Claim-to-evidence tracking</small></span>'

def schema(value): return '<script type="application/ld+json">'+json.dumps(value,separators=(",",":"),ensure_ascii=False).replace("</","<\\/")+'</script>'

def shell(title, desc, path, body, *, page_type="WebPage", extra_schema=None, robots="index,follow"):
    canonical=BASE+path
    graph=[{"@type":page_type,"@id":canonical+"#page","url":canonical,"name":title,"description":desc,"isPartOf":{"@id":BASE+"/#website"},"publisher":{"@id":BASE+"/#organization"}},
      {"@type":"Organization","@id":BASE+"/#organization","name":"Health Research Database","url":BASE+"/","description":"An independent claim-to-evidence index using public research metadata."},
      {"@type":"WebSite","@id":BASE+"/#website","name":"Health Research Database","alternateName":"HRD Claim Ledger","url":BASE+"/","publisher":{"@id":BASE+"/#organization"}}]
    if extra_schema: graph.extend(extra_schema if isinstance(extra_schema,list) else [extra_schema])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><meta name="robots" content="{robots}"><link rel="canonical" href="{canonical}"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{BASE}/assets/og-home.png"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#071b2a"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/assets/v2.css">{schema({"@context":"https://schema.org","@graph":graph})}<script defer src="/assets/v2.js"></script></head><body>
<a class="skip" href="#content">Skip to content</a><header class="site-header"><div class="wrap nav-wrap"><a class="brand" href="/">{logo()}</a><button class="menu-button" aria-expanded="false" aria-controls="nav">Menu</button><nav id="nav" aria-label="Primary"><a href="/claims/">Claims</a><a href="/evidence-map/">Evidence map</a><a href="/trial-radar/">Trial radar</a><a href="/changes/">What's changed</a><a href="/research/">Database</a><a href="/data-download/">Data</a></nav></div></header>
<main id="content">{body}</main>
<footer><div class="wrap footer-grid"><div><a class="brand footer-brand" href="/">{logo()}</a><p>A continuously updated, transparent map of consumer health claims and the human research behind them.</p><p class="fine">Research information only—not medical advice, diagnosis or treatment.</p></div><div><h2>Products</h2><a href="/claims/">Claim Ledger</a><a href="/evidence-map/">Evidence Map</a><a href="/trial-radar/">Trial Radar</a><a href="/changes/">Evidence Changes</a><a href="/healthspan/">Healthspan test</a></div><div><h2>Standards</h2><a href="/methodology/">Methodology</a><a href="/claim-fidelity/">Claim Fidelity</a><a href="/editorial-policy/">Editorial policy</a><a href="/corrections/">Corrections</a><a href="/funding/">Funding & conflicts</a></div><div><h2>About</h2><a href="/about/">About HRD</a><a href="/data-sources/">Data sources</a><a href="/contact/">Contact</a><a href="/data-download/">Open data</a><a href="/resources/inhouse-wellness/">InHouse Wellness</a></div></div><div class="wrap footer-bottom"><span>© {datetime.now().year} Health Research Database</span><span>PubMed and ClinicalTrials.gov are source databases; they do not endorse HRD.</span></div></footer></body></html>'''

def timestamp(stats, label="Research data last refreshed"):
    return f'<div class="timestamp"><span>{esc(label)}</span><time datetime="{esc(stats.get("generated_at") or "")}">{esc(stat_date(stats))}</time></div>'

def crumb(items):
    return '<nav class="crumb" aria-label="Breadcrumb">'+' <span>/</span> '.join(f'<a href="{u}">{esc(t)}</a>' if u else esc(t) for t,u in items)+'</nav>'

def status_pill(claim): return f'<span class="verdict {esc(claim["status_tone"])}">{esc(claim["status"])}</span>'

def paper_card(s):
    return f'<article class="record"><div class="record-meta"><span>{esc(s.get("year") or "Year n/a")}</span><span class="design d-{esc(s.get("design_class","e"))}">{esc(s.get("design_label","Research"))}</span></div><h3><a href="/studies/{esc(s["pmid"])}/">{esc(s["title"])}</a></h3><p>{esc(s.get("journal"))} · PMID {esc(s.get("pmid"))}</p></article>'

def trial_card(t):
    return f'<article class="record"><div class="record-meta"><span class="status-dot">{esc(slug_label(t.get("status")))}</span><span>{esc(t.get("last_update") or "Update n/a")}</span></div><h3><a href="/trials/{esc(t["nct_id"])}/">{esc(t["title"])}</a></h3><p>{esc(t["nct_id"])} · Enrollment: {esc(t.get("enrollment") or "not listed")}</p></article>'

def claim_matches(claim, studies, trials):
    ss=[s for s in studies if claim["topic"] in s.get("topics",[]) and match(s,claim["match_any"])]
    tt=[t for t in trials if claim["topic"] in t.get("topics",[]) and match(t,claim["trial_any"])]
    return ss,tt

def claim_page(claim, studies, trials, topics, stats):
    ss,tt=claim_matches(claim,studies,trials); counts=Counter(s.get("design_class","e") for s in ss); active=sum(t.get("status") in ACTIVE for t in tt)
    profile=''.join(f'<div><span>{esc(k)}</span><strong>{esc(v)}</strong></div>' for k,v in claim["profile"].items())
    rows=''.join(paper_card(s) for s in ss[:12]) or '<div class="empty">No directly matched publications are in the current indexed snapshot.</div>'
    trials_html=''.join(trial_card(t) for t in tt[:8]) or '<div class="empty">No directly matched registered trials are in the current indexed snapshot.</div>'
    query=' OR '.join('"'+x+'"' for x in claim["match_any"])
    citation=f'Health Research Database. “{claim["question"]}” HRD Claim Ledger. Dataset {iso_date(stats)}. Accessed {iso_date(stats)}.'
    receipt={"claim":claim["claim"],"data_refreshed":stats.get("generated_at"),"human_publications_matched":len(ss),"randomized_trials":counts.get("b",0),"systematic_reviews":counts.get("a",0),"registered_trials":len(tt),"active_trials":active,"dataset_version":iso_date(stats)}
    extra={"@type":"ClaimReview","url":BASE+f'/claims/{claim["slug"]}/',"datePublished":"2026-09-18","dateModified":iso_date(stats),"itemReviewed":{"@type":"Claim","appearance":{"@type":"CreativeWork","url":BASE+f'/claims/{claim["slug"]}/'},"author":{"@type":"Organization","name":"Health Research Database"}},"claimReviewed":claim["claim"],"reviewRating":{"@type":"Rating","alternateName":claim["status"],"ratingExplanation":claim["answer"]},"author":{"@id":BASE+"/#organization"}}
    body=f'''<section class="claim-hero"><div class="wrap narrow">{crumb([("Home","/"),("Claim Ledger","/claims/"),(claim["question"],None)])}<div class="kicker">HRD Claim Ledger · Living evidence brief</div><h1>{esc(claim["question"])}</h1><div class="claim-summary">{status_pill(claim)}<p>{esc(claim["answer"])}</p></div>{timestamp(stats,"Source search last executed")}</div></section>
<section class="section"><div class="wrap split"><div><div class="section-title"><span>01</span><div><div class="kicker">Evidence profile</div><h2>What the evidence can—and cannot—support</h2></div></div><div class="profile-grid">{profile}</div><div class="callout"><strong>Important uncertainty</strong><p>{esc(claim["uncertainty"])}</p></div></div><aside class="fidelity-card"><div class="kicker light">HRD Claim Fidelity</div><div class="fidelity-level">{esc(claim["fidelity"])}</div><h2>Does the research match the words?</h2><p>{esc(claim["fidelity_note"])}</p><a href="/claim-fidelity/">How Claim Fidelity works →</a></aside></div></section>
<section class="section receipt-section"><div class="wrap"><div class="section-title"><span>02</span><div><div class="kicker">Research Receipt</div><h2>An auditable count, not “studies show”</h2></div></div><div class="receipt"><div class="receipt-top"><div><span>Claim checked</span><strong>{esc(claim["claim"])}</strong></div><div><span>Dataset edition</span><strong>{esc(iso_date(stats))}</strong></div></div><div class="receipt-stats"><div><strong>{len(ss)}</strong><span>matched publications</span></div><div><strong>{counts.get("b",0)}</strong><span>randomized trials</span></div><div><strong>{counts.get("a",0)}</strong><span>reviews / meta-analyses</span></div><div><strong>{len(tt)}</strong><span>registered trials</span></div><div><strong>{active}</strong><span>active trials</span></div></div><details><summary>Reproduce this receipt</summary><div class="detail-content"><p><b>Included:</b> Records in the {esc(claim["intervention"])} topic whose high-signal metadata contains at least one outcome term below.</p><p><b>Outcome expression:</b> <code>{esc(query)}</code></p><p><b>Excluded:</b> Records outside the intervention topic, animal-only records rejected by the source query, and records without an outcome-term match. This is a reproducible index, not a systematic review.</p><a class="button secondary" href="/api/v1/claims/{esc(claim["slug"])}.json">Download receipt JSON</a></div></details></div></div></section>
<section class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">Matched publications</div><h2>Why these records count</h2></div><p>Each record matched the intervention topic and at least one claim-specific outcome term. Open a record for source metadata and inclusion provenance.</p></div><div class="record-list">{rows}</div></div></section>
<section class="section alt"><div class="wrap"><div class="section-head"><div><div class="kicker">Trial Radar</div><h2>Evidence that may change the answer</h2></div><p>Registration is not a result. Status and dates come from ClinicalTrials.gov.</p></div><div class="record-list">{trials_html}</div></div></section>
<section class="section"><div class="wrap cite-box"><div><div class="kicker">Cite this page</div><h2>Make the evidence trail portable.</h2></div><div><p id="citation">{esc(citation)}</p><button class="button secondary" data-copy="#citation">Copy citation</button> <a class="button secondary" href="/api/v1/claims/{esc(claim["slug"])}.json">JSON</a></div></div></section>'''
    return shell(f'{claim["question"]} — HRD Claim Ledger',claim["answer"],f'/claims/{claim["slug"]}/',body,page_type="MedicalWebPage",extra_schema=extra), receipt

def home(claims, studies, trials, topics, stats):
    featured=''.join(f'<a class="claim-card" href="/claims/{esc(c["slug"])}/"><span>{esc(c["intervention"])}</span><h3>{esc(c["question"])}</h3>{status_pill(c)}<p>{esc(c["answer"][:165])}…</p><b>Open Research Receipt →</b></a>' for c in claims[:6])
    recent=''.join(paper_card(s) for s in studies[:4])
    active=sum(t.get("status") in ACTIVE for t in trials)
    body=f'''<section class="home-hero"><div class="wrap hero-grid"><div><div class="kicker light">The claim-to-evidence index</div><h1>Check a health claim against <em>human research.</em></h1><p>See the current answer, exactly what was studied, where a claim overreaches, and what new evidence could change it.</p><form class="claim-search" action="/claims/" role="search"><label for="claim-search">Search claims and indexed research</label><div><input id="claim-search" name="q" type="search" placeholder="Try: Do cold plunges raise testosterone?" autocomplete="off"><button>Check the evidence</button></div><div id="claim-suggestions" class="suggestions"></div></form><div class="popular"><span>Popular:</span><a href="/claims/saunas-lower-blood-pressure/">sauna + blood pressure</a><a href="/claims/cold-plunges-increase-testosterone/">cold + testosterone</a><a href="/claims/red-light-therapy-helps-knee-pain/">red light + knee pain</a></div></div><aside class="receipt-preview"><div class="receipt-stamp">Research Receipt</div><span>Current public index</span><strong>{len(studies)+len(trials):,}</strong><p>human publications and registered trials</p><dl><div><dt>Randomized trials</dt><dd>{sum(s.get("design_class")=="b" for s in studies):,}</dd></div><div><dt>Systematic reviews</dt><dd>{sum(s.get("design_class")=="a" for s in studies):,}</dd></div><div><dt>Active trials</dt><dd>{active:,}</dd></div><div><dt>Claims tracked</dt><dd>{len(claims)}</dd></div></dl><small>Refreshed {esc(stat_date(stats))}</small></aside></div></section>
<section class="index-strip"><div class="wrap"><div><strong>{len(studies):,}</strong><span>publications</span></div><div><strong>{len(trials):,}</strong><span>registered trials</span></div><div><strong>{sum(s.get("design_class")=="b" for s in studies):,}</strong><span>randomized trials</span></div><div><strong>{sum(s.get("design_class")=="a" for s in studies):,}</strong><span>research syntheses</span></div><div><strong>{len(topics)}</strong><span>interventions</span></div></div></section>
<section class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">Claims recently assessed</div><h2>Start with the words people actually use.</h2></div><a href="/claims/">View all claims →</a></div><div class="claim-grid">{featured}</div></div></section>
<section class="section dark"><div class="wrap product-grid"><div><span class="number">01</span><h2>Claim Fidelity</h2><p>Does the cited research match the intervention, population, dose, duration and outcome in the claim?</p><a href="/claim-fidelity/">Inspect the framework →</a></div><div><span class="number">02</span><h2>Trial Radar</h2><p>Watch new, recruiting and recently completed trials before their findings become headlines.</p><a href="/trial-radar/">See trials to watch →</a></div><div><span class="number">03</span><h2>Evidence Changes</h2><p>See newly indexed records, status changes, corrections and claim reassessments.</p><a href="/changes/">See what changed →</a></div></div></section>
<section class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">Latest indexed research</div><h2>The source layer stays visible.</h2></div><a href="/research/">Search the database →</a></div><div class="record-list">{recent}</div></div></section>
<section class="section quiz-tease"><div class="wrap split"><div><div class="kicker">Secondary product</div><h2>How closely do your habits align with public-health guidance?</h2><p>The Healthspan Habits Test remains a transparent, shareable habit-alignment exercise—not a biological-age test, diagnosis or lifespan prediction.</p><a class="button primary" href="/healthspan/">Take the 2-minute test</a></div><div class="quiz-score"><span>Example result</span><strong>82<small>/100</small></strong><p>Every question links back to its guidance and evidence context.</p></div></div></section>'''
    return shell("Health Research Database — Check a Health Claim Against Human Research","A continuously updated claim-to-evidence index. Check health claims, inspect Claim Fidelity, reproduce Research Receipts and track clinical trials.","/",body)

def claims_index(claims, studies, trials, stats):
    cards=[]
    for c in claims:
        ss,tt=claim_matches(c,studies,trials)
        cards.append(f'<a class="claim-row" href="/claims/{esc(c["slug"])}/" data-search="{esc((c["question"]+" "+c["intervention"]+" "+c["outcome"]).lower())}"><div>{status_pill(c)}<h2>{esc(c["question"])}</h2><p>{esc(c["intervention"])} · {esc(c["outcome"])}</p></div><dl><div><dt>Publications</dt><dd>{len(ss)}</dd></div><div><dt>RCTs</dt><dd>{sum(s.get("design_class")=="b" for s in ss)}</dd></div><div><dt>Fidelity</dt><dd>{esc(c["fidelity"])}</dd></div></dl><b>View receipt →</b></a>')
    body=f'<section class="page-hero"><div class="wrap narrow">{crumb([("Home","/"),("Claim Ledger",None)])}<div class="kicker">HRD Claim Ledger</div><h1>Health claims, checked against the source layer.</h1><p>Each living brief separates what research directly tested from what marketing, headlines or everyday language imply.</p>{timestamp(stats)}</div></section><section class="section"><div class="wrap"><label class="filter-search">Filter claims<input type="search" placeholder="Search intervention, outcome or question" data-claim-filter></label><div class="claim-list">{"".join(cards)}</div></div></section>'
    return shell("Claim Ledger — Health Research Database","Living evidence briefs with current answers, Claim Fidelity and reproducible Research Receipts.","/claims/",body)

def evidence_map(claims, studies, trials, topics, stats):
    outcomes=[]
    for c in claims:
        ss,tt=claim_matches(c,studies,trials); outcomes.append((c,len(ss),sum(s.get("design_class")=="b" for s in ss),sum(s.get("design_class")=="a" for s in ss),len(tt)))
    rows=''.join(f'<tr><th><a href="/claims/{esc(c["slug"])}/">{esc(c["outcome"])}</a><small>{esc(c["intervention"])}</small></th><td>{n}</td><td>{r}</td><td>{v}</td><td>{t}</td><td>{esc(c["fidelity"])}</td></tr>' for c,n,r,v,t in outcomes)
    topic_cards=[]
    for t in topics:
        ss=[s for s in studies if t["slug"] in s.get("topics",[])]; tt=[x for x in trials if t["slug"] in x.get("topics",[])]
        topic_cards.append(f'<a class="topic-card" href="/topics/{esc(t["slug"])}/"><span>{len(ss)} publications · {len(tt)} trials</span><h2>{esc(t["name"])}</h2><p>{esc(t["short"])}</p><b>Open dashboard →</b></a>')
    body=f'<section class="page-hero"><div class="wrap narrow">{crumb([("Home","/"),("Evidence map",None)])}<div class="kicker">Intervention × outcome</div><h1>See what has actually been studied.</h1><p>Counts are generated from the current indexed snapshot and link to the exact claim-level receipt behind them. Volume is not proof of benefit.</p>{timestamp(stats)}</div></section><section class="section"><div class="wrap"><div class="table-wrap"><table class="matrix"><thead><tr><th>Claim outcome</th><th>Matched studies</th><th>RCTs</th><th>Reviews</th><th>Registered trials</th><th>Claim Fidelity</th></tr></thead><tbody>{rows}</tbody></table></div></div></section><section class="section alt"><div class="wrap"><div class="section-head"><div><div class="kicker">Intervention dashboards</div><h2>Explore the indexed source layer.</h2></div></div><div class="topic-grid">{"".join(topic_cards)}</div></div></section>'
    return shell("Evidence Map — Health Research Database","An intervention-by-outcome map of indexed human studies, randomized trials, reviews and registered trials.","/evidence-map/",body)

def trial_radar(trials, stats):
    active=[t for t in trials if t.get("status") in ACTIVE]; completed=[t for t in trials if t.get("status")=="COMPLETED"]
    coming=[t for t in active if (t.get("completion_date") or "")[:4] in {str(datetime.now().year),str(datetime.now().year+1)}]
    body=f'<section class="page-hero"><div class="wrap narrow">{crumb([("Home","/"),("Trial Radar",None)])}<div class="kicker">HRD Trial Radar</div><h1>Watch the evidence before it becomes a headline.</h1><p>Newly registered, actively recruiting and recently completed studies from ClinicalTrials.gov. Registration describes a protocol—not a positive result.</p>{timestamp(stats,"ClinicalTrials.gov data retrieved")}</div></section><section class="index-strip"><div class="wrap"><div><strong>{len(active)}</strong><span>active trials</span></div><div><strong>{sum(t.get("status")=="RECRUITING" for t in trials)}</strong><span>recruiting</span></div><div><strong>{len(coming)}</strong><span>expected by next year</span></div><div><strong>{len(completed)}</strong><span>completed in index</span></div></div></section><section class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">Active now</div><h2>Recruiting and ongoing trials</h2></div></div><div class="record-list">{"".join(trial_card(t) for t in active[:30]) or "<div class=empty>No active trials in the current snapshot.</div>"}</div></div></section><section class="section alt"><div class="wrap"><div class="section-head"><div><div class="kicker">Readouts ahead</div><h2>Trials expected to complete soon</h2></div></div><div class="record-list">{"".join(trial_card(t) for t in coming[:20]) or "<div class=empty>No near-term completion dates matched.</div>"}</div></div></section>'
    return shell("Trial Radar — Health Research Database","Track recruiting, ongoing and recently completed consumer health and wellness trials.","/trial-radar/",body)

def changes_page(studies,trials,stats):
    fresh=studies[:12]; changed=sorted(trials,key=lambda x:x.get("last_update","") or "",reverse=True)[:12]
    body=f'<section class="page-hero"><div class="wrap narrow">{crumb([("Home","/"),("What changed",None)])}<div class="kicker">Evidence Changes</div><h1>What changed in health research?</h1><p>A public activity ledger for new evidence, trial updates, corrections and future claim reassessments.</p>{timestamp(stats)}</div></section><section class="section"><div class="wrap timeline"><div><div class="kicker">New publications</div><h2>Recently indexed</h2><div class="record-list">{"".join(paper_card(s) for s in fresh)}</div></div><div><div class="kicker">Registry activity</div><h2>Recently updated trials</h2><div class="record-list">{"".join(trial_card(t) for t in changed)}</div></div></div></section><section class="section alt"><div class="wrap statement"><div><span>Transparent by design</span><h2>Corrections and removals belong in the record.</h2></div><p>When a record is reclassified, removed as irrelevant or a claim assessment changes, HRD will publish the reason here instead of silently rewriting history. The first retained baseline is this dataset edition.</p></div></section>'
    return shell("What's Changed — Health Research Database","New research, trial status changes, corrections and claim reassessments in the HRD evidence index.","/changes/",body)

def topic_page(topic,studies,trials,claims,stats):
    ss=[s for s in studies if topic["slug"] in s.get("topics",[])]; tt=[t for t in trials if topic["slug"] in t.get("topics",[])]; counts=Counter(s.get("design_class","e") for s in ss)
    claim_links=''.join(f'<a class="mini-claim" href="/claims/{esc(c["slug"])}/">{esc(c["question"])}<span>{esc(c["status"])}</span></a>' for c in claims if c["topic"]==topic["slug"])
    trend=Counter(int(s["year"]) for s in ss if str(s.get("year","")).isdigit()); years=sorted(y for y in trend if y>=2015); maxn=max([trend[y] for y in years] or [1]); bars=''.join(f'<div><i style="height:{max(4,int(trend[y]/maxn*100))}%"></i><span>{str(y)[-2:]}</span><b>{trend[y]}</b></div>' for y in years)
    mix=''.join(f'<div><strong>{counts.get(k,0)}</strong><span>{esc(v)}</span></div>' for k,v in DESIGNS.items())
    body=f'<section class="page-hero"><div class="wrap narrow">{crumb([("Home","/"),("Evidence map","/evidence-map/"),(topic["name"],None)])}<div class="kicker">Intervention dashboard</div><h1>{esc(topic["name"])}</h1><p>{esc(topic["short"])}</p>{timestamp(stats)}</div></section><section class="index-strip"><div class="wrap"><div><strong>{len(ss)}</strong><span>publications</span></div><div><strong>{len(tt)}</strong><span>registered trials</span></div><div><strong>{counts.get("b",0)}</strong><span>randomized trials</span></div><div><strong>{counts.get("a",0)}</strong><span>reviews</span></div></div></section><section class="section"><div class="wrap split"><div><div class="kicker">Study-design mix</div><h2>What kinds of evidence exist?</h2><div class="metric-list">{mix}</div><p class="fine">Classification uses PubMed publication types and methods-language heuristics. Counts describe research volume, not effectiveness.</p></div><div><div class="kicker">Research over time</div><h2>Indexed publications by year</h2><div class="bar-chart">{bars or "<div class=empty>Insufficient dated records.</div>"}</div></div></div></section><section class="section alt"><div class="wrap"><div class="section-head"><div><div class="kicker">Claim Ledger</div><h2>Questions tied to this intervention</h2></div></div><div class="mini-claims">{claim_links or "<p class=empty>No claim brief has been published for this intervention yet.</p>"}</div></div></section><section class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">Source records</div><h2>Recently indexed publications</h2></div></div><div class="record-list">{"".join(paper_card(s) for s in ss[:30])}</div></div></section><section class="section alt"><div class="wrap"><div class="section-head"><div><div class="kicker">Trial Radar</div><h2>Registered trials</h2></div></div><div class="record-list">{"".join(trial_card(t) for t in tt[:20])}</div></div></section>'
    return shell(f'{topic["name"]} Research Dashboard — HRD',topic["short"],f'/topics/{topic["slug"]}/',body)

def study_page(s,stats):
    topics=', '.join(f'<a href="/topics/{esc(slug)}/">{esc(name)}</a>' for slug,name in zip(s.get("topics",[]),s.get("topic_names",[]))) or "Not classified"
    reason=s.get("match_reason") or "Matched through intervention terms in title, keywords or MeSH metadata."
    body=f'<section class="page-hero compact"><div class="wrap narrow">{crumb([("Home","/"),("Research database","/research/"),("PMID "+s["pmid"],None)])}<span class="design d-{esc(s.get("design_class","e"))}">{esc(s.get("design_label","Research record"))}</span><h1>{esc(s["title"])}</h1><p>{esc(s.get("journal"))} · {esc(s.get("year") or "Year not indexed")}</p>{timestamp(stats)}</div></section><section class="section"><div class="wrap split"><div class="detail-card"><div class="kicker">Source metadata</div><h2>Publication record</h2><dl class="definition"><div><dt>PMID</dt><dd>{esc(s["pmid"])}</dd></div><div><dt>Authors</dt><dd>{esc(", ".join(s.get("authors") or []) or "Not listed")}</dd></div><div><dt>Journal</dt><dd>{esc(s.get("journal"))}</dd></div><div><dt>Publication types</dt><dd>{esc(", ".join(s.get("publication_types") or []) or "Not specified")}</dd></div><div><dt>Indexed topics</dt><dd>{topics}</dd></div><div><dt>DOI</dt><dd>{esc(s.get("doi") or "Not listed")}</dd></div></dl><a class="button primary" href="{esc(s["pubmed_url"])}" rel="noopener">Open primary PubMed record ↗</a></div><aside class="detail-card"><div class="kicker">Inclusion provenance</div><h2>Why this record is indexed</h2><p>{esc(reason)}</p><dl class="definition"><div><dt>Classification</dt><dd>{esc(s.get("design_label"))}</dd></div><div><dt>Source</dt><dd>{esc(s.get("classification_source") or "PubMed metadata")}</dd></div><div><dt>Confidence</dt><dd>{esc(s.get("classifier_confidence") or "Legacy record; refresh pending")}</dd></div></dl><p class="notice">This metadata page does not summarize the paper&#39;s findings. Read the primary source before drawing a clinical conclusion.</p><a href="/contact/#indexing">Report an indexing issue →</a></aside></div></section>'
    return shell(f'{s["title"]} — PMID {s["pmid"]}',f'Indexed PubMed record {s["pmid"]}: {s["title"]}',f'/studies/{s["pmid"]}/',body,page_type="MedicalScholarlyArticle")

def trial_page(t,stats):
    body=f'<section class="page-hero compact"><div class="wrap narrow">{crumb([("Home","/"),("Trial Radar","/trial-radar/"),(t["nct_id"],None)])}<div class="kicker">ClinicalTrials.gov record</div><h1>{esc(t["title"])}</h1><p>{esc(slug_label(t.get("status")))} · {esc(t["nct_id"])}</p>{timestamp(stats,"ClinicalTrials.gov data retrieved")}</div></section><section class="section"><div class="wrap split"><div class="detail-card"><h2>Protocol record</h2><dl class="definition"><div><dt>NCT ID</dt><dd>{esc(t["nct_id"])}</dd></div><div><dt>Status</dt><dd>{esc(slug_label(t.get("status")))}</dd></div><div><dt>Study type</dt><dd>{esc(slug_label(t.get("study_type")))}</dd></div><div><dt>Enrollment</dt><dd>{esc(t.get("enrollment") or "Not listed")}</dd></div><div><dt>Conditions</dt><dd>{esc(", ".join(t.get("conditions") or []) or "Not listed")}</dd></div><div><dt>Interventions</dt><dd>{esc(", ".join(x.get("name","") for x in t.get("interventions",[]) or []) or "Not listed")}</dd></div><div><dt>Completion date</dt><dd>{esc(t.get("completion_date") or "Not listed")}</dd></div><div><dt>Last registry update</dt><dd>{esc(t.get("last_update") or "Not listed")}</dd></div></dl><a class="button primary" href="{esc(t["url"])}" rel="noopener">Open ClinicalTrials.gov record ↗</a></div><aside class="detail-card"><div class="kicker">Protocol ≠ result</div><h2>A registered study is not a positive finding.</h2><p>Registration documents a planned, active or completed study. It does not show that an intervention worked. Some completed trials never publish journal results.</p><a href="/methodology/#trials">How Trial Radar works →</a></aside></div></section>'
    return shell(f'{t["title"]} — {t["nct_id"]}',f'ClinicalTrials.gov record {t["nct_id"]}: {t["title"]}',f'/trials/{t["nct_id"]}/',body)

def simple_page(path,title,kicker,intro,sections,stats=None):
    blocks=''.join(f'<section class="section{(" alt" if i%2 else "")}"><div class="wrap prose"><div class="kicker">{esc(head)}</div>{content}</div></section>' for i,(head,content) in enumerate(sections))
    ts=timestamp(stats) if stats else ""
    body=f'<section class="page-hero"><div class="wrap narrow">{crumb([("Home","/"),(title,None)])}<div class="kicker">{esc(kicker)}</div><h1>{esc(title)}</h1><p>{intro}</p>{ts}</div></section>{blocks}'
    return shell(f'{title} — Health Research Database',re.sub('<[^>]+>','',intro),path,body)

def redirect_page(source,target):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Moved — Health Research Database</title><meta name="robots" content="noindex,follow"><link rel="canonical" href="{BASE}{target}"><meta http-equiv="refresh" content="0;url={target}"><script>location.replace({json.dumps(target)})</script></head><body><p>This page moved to <a href="{target}">{BASE}{target}</a>.</p></body></html>'''

def research_page(studies,trials,stats):
    body=f'<section class="page-hero"><div class="wrap narrow">{crumb([("Home","/"),("Research database",None)])}<div class="kicker">Source-layer search</div><h1>Search the indexed research.</h1><p>Filter publication titles, journals, authors, MeSH headings and trial metadata. Primary content is rendered below; search only narrows it.</p>{timestamp(stats)}</div></section><section class="section"><div class="wrap"><label class="filter-search">Search {len(studies)+len(trials):,} indexed records<input type="search" placeholder="Try: blood pressure, sleep, soreness" data-record-filter></label><div class="record-list searchable-records">{"".join(paper_card(s) for s in studies[:150])}</div><p class="fine">The HTML view shows the 150 most recent publications. Download the complete dataset or use the JSON endpoint for all records.</p><a class="button secondary" href="/data/studies.json">Complete studies JSON</a></div></section>'
    return shell("Research Database — Health Research Database","Search HRD's normalized PubMed and ClinicalTrials.gov metadata index.","/research/",body)

def data_page(studies,trials,claims,stats):
    files=[]
    for name,label,fmt,count in [("studies.json","Studies JSON","JSON",len(studies)),("studies.csv","Studies CSV","CSV",len(studies)),("trials.json","Trials JSON","JSON",len(trials)),("trials.csv","Trials CSV","CSV",len(trials)),("claims.json","Claim definitions","JSON",len(claims))]:
        p=DATA/name; size=p.stat().st_size if p.exists() else 0; checksum=hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else "pending"
        files.append(f'<article class="dataset"><span>{fmt} · {count:,} rows/records</span><h2>{label}</h2><p>{size/1024:.1f} KB · SHA-256 <code>{checksum[:16]}…</code></p><a class="button secondary" href="/data/{name}" download>Download {fmt}</a></article>')
    extra={"@type":"Dataset","name":"Health Research Database current research index","description":"Normalized public metadata from PubMed and ClinicalTrials.gov organized by consumer wellness intervention and claim.","url":BASE+"/data-download/","version":iso_date(stats),"dateModified":iso_date(stats),"license":"https://creativecommons.org/licenses/by/4.0/","creator":{"@id":BASE+"/#organization"},"distribution":[{"@type":"DataDownload","encodingFormat":"application/json","contentUrl":BASE+"/data/studies.json"},{"@type":"DataDownload","encodingFormat":"text/csv","contentUrl":BASE+"/data/studies.csv"},{"@type":"DataDownload","encodingFormat":"application/json","contentUrl":BASE+"/data/trials.json"}]}
    body=f'<section class="page-hero"><div class="wrap narrow">{crumb([("Home","/"),("Open data",None)])}<div class="kicker">HRD Open Data</div><h1>Inspect, download and cite the evidence index.</h1><p>Current normalized metadata, claim definitions and machine-readable Research Receipts. Licensed for reuse with attribution.</p>{timestamp(stats)}</div></section><section class="section"><div class="wrap dataset-grid">{"".join(files)}</div></section><section class="section alt"><div class="wrap prose"><div class="kicker">Suggested citation</div><h2>Cite the dataset edition, not an undated moving target.</h2><p><code>Health Research Database. HRD research index, edition {iso_date(stats)}. {BASE}/data-download/. Licensed CC BY 4.0.</code></p><h2>Fields and provenance</h2><p>Study records include PMID, title, authors, journal, year, DOI, publication types, MeSH headings, topic membership, design classification and primary-source URL. Trial records include NCT ID, status, enrollment, conditions, interventions, dates and source URL.</p><p>HRD republishes metadata, not full journal articles. Original source rights remain with their owners.</p></div></section>'
    return shell("Open Data — Health Research Database","Download versioned HRD studies, trials and claim metadata with checksums, licensing and citation guidance.","/data-download/",body,extra_schema=extra)

def make_feeds(studies,trials,stats):
    def rss(items,title,path,is_trial=False):
        entries=[]
        for x in items[:50]:
            ident=x.get("nct_id") if is_trial else x.get("pmid"); url=BASE+(f'/trials/{ident}/' if is_trial else f'/studies/{ident}/')
            entries.append(f'<item><title>{esc(x.get("title"))}</title><link>{url}</link><guid>{url}</guid><description>{esc("ClinicalTrials.gov record" if is_trial else x.get("journal"))}</description></item>')
        return '<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>'+esc(title)+'</title><link>'+BASE+path+'</link><description>Latest HRD source records</description>'+''.join(entries)+'</channel></rss>'
    write("feed/new-studies.xml",rss(studies,"HRD — New studies","/feed/new-studies.xml")); write("feed/new-trials.xml",rss(trials,"HRD — Trial updates","/feed/new-trials.xml",True))

def make_sitemaps(static_paths,claims,topics,studies,trials,stats):
    date=iso_date(stats)
    def urlset(paths): return '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{BASE}{p}</loc><lastmod>{date}</lastmod></url>\n' for p in paths)+'</urlset>\n'
    groups={"pages":static_paths,"claims":[f'/claims/{c["slug"]}/' for c in claims],"topics":[f'/topics/{t["slug"]}/' for t in topics],"studies":[f'/studies/{s["pmid"]}/' for s in studies],"trials":[f'/trials/{t["nct_id"]}/' for t in trials]}
    for name,paths in groups.items(): write(f"sitemap-{name}.xml",urlset(paths))
    index='<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<sitemap><loc>{BASE}/sitemap-{name}.xml</loc><lastmod>{date}</lastmod></sitemap>\n' for name in groups)+'</sitemapindex>\n'; write("sitemap.xml",index)

def main():
    topics=load("topics.json",[]); studies=clean_and_classify_legacy(load("studies.json",[])); trials=load("trials.json",[]); claims=load("claims.json",[]); stats=load("stats.json",{})
    valid_claims={c["slug"] for c in claims}
    claims_dir=ROOT/"claims"
    if claims_dir.exists():
        for p in claims_dir.iterdir():
            if p.is_dir() and p.name not in valid_claims: shutil.rmtree(p)
    api_claims=ROOT/"api/v1/claims"
    if api_claims.exists():
        for p in api_claims.glob("*.json"):
            if p.stem not in valid_claims and p.name!="index.json": p.unlink()
    dump("data/studies.json",studies)
    stats["total_studies"]=len(studies); stats["total_trials"]=len(trials); stats["active_trials"]=sum(t.get("status") in ACTIVE for t in trials)
    stats["topics"]={t["slug"]:{"studies":sum(t["slug"] in s.get("topics",[]) for s in studies),"trials":sum(t["slug"] in x.get("topics",[]) for x in trials),"designs":dict(Counter(s.get("design_class","e") for s in studies if t["slug"] in s.get("topics",[])))} for t in topics}
    dump("data/stats.json",stats)
    with (DATA/"studies.csv").open("w",newline="",encoding="utf-8") as f:
        w=csv.writer(f); w.writerow(["pmid","title","year","journal","design","doi","topics","pubmed_url"])
        for s in studies: w.writerow([s.get("pmid"),s.get("title"),s.get("year"),s.get("journal"),s.get("design_label"),s.get("doi"),"|".join(s.get("topic_names",[])),s.get("pubmed_url")])
    write("index.html",home(claims,studies,trials,topics,stats)); write("claims/index.html",claims_index(claims,studies,trials,stats)); write("evidence-map/index.html",evidence_map(claims,studies,trials,topics,stats)); write("trial-radar/index.html",trial_radar(trials,stats)); write("changes/index.html",changes_page(studies,trials,stats)); write("research/index.html",research_page(studies,trials,stats)); write("data-download/index.html",data_page(studies,trials,claims,stats))
    receipts=[]
    for c in claims:
        page,receipt=claim_page(c,studies,trials,topics,stats); write(f'claims/{c["slug"]}/index.html',page); dump(f'api/v1/claims/{c["slug"]}.json',receipt); receipts.append(receipt)
    dump("api/v1/claims/index.json",receipts); dump("api/v1/topics/index.json",[{"slug":t["slug"],"name":t["name"],"url":BASE+f'/topics/{t["slug"]}/'} for t in topics]); dump("api/v1/status.json",{"status":"operational","dataset_version":iso_date(stats),"generated_at":stats.get("generated_at"),"records":len(studies)+len(trials)})
    for t in topics: write(f'topics/{t["slug"]}/index.html',topic_page(t,studies,trials,claims,stats))
    for s in studies: write(f'studies/{s["pmid"]}/index.html',study_page(s,stats))
    for t in trials: write(f'trials/{t["nct_id"]}/index.html',trial_page(t,stats))
    pages={
      "methodology/index.html":simple_page("/methodology/","Methodology","How HRD works","HRD maps consumer health claims to public research metadata. It is an evidence-discovery system, not a clinical guideline or automated medical verdict.",[("Pipeline","<h2>From source record to claim receipt</h2><ol><li>Retrieve human-research candidates from PubMed and registered studies from ClinicalTrials.gov.</li><li>Require intervention-specific terms in high-signal metadata.</li><li>Classify study design from authoritative publication types, then methods-language heuristics.</li><li>Match claims only when outcome terms appear inside an already-matched intervention topic.</li><li>Publish counts, exact terms, dates and source links so readers can reproduce the result.</li></ol>"),("Research Receipt","<h2>What a count means</h2><p>A Research Receipt is a reproducible count within HRD's current indexed snapshot. It is not a systematic review, risk-of-bias assessment or proof of efficacy. Records can overlap topics and claims.</p>"),("Trials","<h2 id=trials>Registry records are not results</h2><p>Trial Radar reports registry status, dates and interventions. Registration does not show that a study succeeded, and estimated completion dates can change.</p>"),("Limitations","<h2>Known boundaries</h2><p>PubMed is not the whole literature. Metadata can be incomplete. Keyword matching can miss eligible records or include marginal ones. Claim answers are cautious editorial syntheses and should be reviewed as the corpus changes.</p>")],stats),
      "claim-fidelity/index.html":simple_page("/claim-fidelity/","Claim Fidelity","A framework for evidence directness","Claim Fidelity asks whether cited research actually matches the words in a health claim. A large literature can coexist with poor claim fidelity.",[("Eight dimensions","<h2>What HRD compares</h2><div class=dimension-grid><div><b>Intervention</b><span>Finnish sauna ≠ infrared sauna</span></div><div><b>Population</b><span>Heart-failure patients ≠ healthy adults</span></div><div><b>Dose</b><span>Daily protocol ≠ occasional use</span></div><div><b>Duration</b><span>Acute response ≠ durable benefit</span></div><div><b>Comparator</b><span>No treatment ≠ active treatment</span></div><div><b>Outcome</b><span>Soreness ≠ muscle recovery</span></div><div><b>Measurement</b><span>Biomarker ≠ clinical outcome</span></div><div><b>Setting</b><span>Supervised study ≠ home device</span></div></div>"),("Ratings","<h2>High, moderate or low</h2><p><b>High</b> means the central intervention and outcome closely match. <b>Moderate</b> signals material differences or incomplete reporting. <b>Low</b> means the claim substantially extrapolates beyond what was studied. Fidelity does not grade study quality or effectiveness.</p>"),("Example","<h2>Research depth and fidelity are separate</h2><p>Traditional sauna may have a large cardiovascular literature while a claim about infrared-sauna longevity has low fidelity. The broader research volume does not repair the modality mismatch.</p>")]),
      "about/index.html":simple_page("/about/","About Health Research Database","Independent evidence infrastructure","Health Research Database is a public, continuously updated map between consumer health claims, human research records and registered clinical trials.",[("Purpose","<h2>Why HRD exists</h2><p>Research is often compressed into the phrase “studies show.” HRD makes the missing details visible: which studies, what intervention, what outcome, what changed and how closely the source evidence matches the claim.</p>"),("Scope","<h2>Focused before broad</h2><p>The first release concentrates on sauna and passive heat, cold-water immersion, contrast therapy, photobiomodulation, floatation and massage. HRD deepens these topics before expanding indiscriminately.</p>"),("Independence","<h2>Research first</h2><p>Claim, topic, study and trial pages contain no shopping links. Commercial relationships and project funding are disclosed separately.</p>")]),
      "editorial-policy/index.html":simple_page("/editorial-policy/","Editorial Policy","Governance","HRD separates source metadata, automated classification and editorial interpretation so readers can see where each statement comes from.",[("Labels","<h2>Three provenance layers</h2><p><b>Source metadata</b> comes from PubMed or ClinicalTrials.gov. <b>Structured classification</b> is rule-assisted and identified as such. <b>Claim answers</b> are editorial summaries designed to state uncertainty plainly.</p>"),("Standards","<h2>What we do not do</h2><p>We do not infer effectiveness from publication counts, treat registry entries as results, collapse distinct interventions into one, invent reviewer credentials or present HRD as medical advice.</p>"),("Updates","<h2>Living reviews</h2><p>Material new evidence can trigger a reassessment. Changes and corrections should be recorded publicly with the date and reason.</p>")]),
      "corrections/index.html":simple_page("/corrections/","Corrections","Public error ledger","Classification and synthesis errors should be visible, correctable and preserved in an audit trail.",[("Current ledger","<h2>No published corrections in this edition</h2><p>This is the first retained public baseline for the rebuilt Claim Ledger. Future corrections will state the affected page, original text or classification, corrected version, reason and date.</p>"),("Report","<h2>Found a problem?</h2><p>Use the contact page to report a wrong topic, incorrect study type, duplicate record, missing study or claim-fidelity concern. Include the PMID, DOI or NCT ID when possible.</p><p><a class=button href=/contact/#indexing>Report an indexing issue</a></p>")]),
      "funding/index.html":simple_page("/funding/","Funding & Conflicts","Disclosure","Transparency matters more than manufactured neutrality. This page records the relationship between HRD and its operator's commercial interests.",[("Funding","<h2>How the project is supported</h2><p>HRD is independently operated and currently supported by its owner. It does not accept payment to change a claim verdict, include a study or alter a Research Receipt.</p>"),("Commercial relationship","<h2>InHouse Wellness</h2><p>The site operator has a commercial relationship with InHouse Wellness, a retailer of saunas, cold plunges and related wellness equipment. Research pages are separated from the single retailer-information page, and no product shopping links appear within claim or evidence pages.</p>"),("Conflicts policy","<h2>What the separation requires</h2><p>Commerce does not determine inclusion criteria, study classification, Claim Fidelity or editorial conclusions. Potential conflicts should be disclosed on the relevant governance pages.</p>")]),
      "data-sources/index.html":simple_page("/data-sources/","Data Sources","Primary-source provenance","HRD builds on public research infrastructure and links every indexed record back to its source.",[("PubMed","<h2>Publication metadata</h2><p>PubMed supplies identifiers, titles, authors, journals, publication types, MeSH headings and other bibliographic metadata. HRD does not republish full journal articles.</p>"),("ClinicalTrials.gov","<h2>Registered trial metadata</h2><p>ClinicalTrials.gov supplies protocol titles, recruitment status, enrollment, interventions, conditions and dates. Registry information can change and does not establish results.</p>"),("Cadence","<h2>Twice-weekly refresh</h2><p>The automated updater runs Mondays and Thursdays. Visible timestamps report when the current source search was executed.</p>")]),
      "contact/index.html":simple_page("/contact/","Contact & Indexing Reports","Quality control","Researchers and readers can help improve the index by reporting a classification error, duplicate, missing record or unclear claim assessment.",[("Indexing","<h2 id=indexing>Report an indexing issue</h2><p>Email <a href=mailto:research@healthresearchdatabase.com>research@healthresearchdatabase.com</a> with the page URL and, when available, the PMID, DOI or NCT ID. State whether the issue is a wrong topic, wrong study design, duplicate, missing record or claim-fidelity concern.</p>"),("Corrections","<h2>What happens next</h2><p>Substantive verified corrections are added to the public corrections ledger. HRD does not promise individual medical guidance or interpret personal health information.</p>")]),
      "resources/inhouse-wellness/index.html":simple_page("/resources/inhouse-wellness/","InHouse Wellness","Retailer information","A separate resource page about the wellness-equipment retailer associated with this site's operator. This page is outside the evidence and Claim Ledger layer.",[("About the retailer","<h2>Home sauna and cold-plunge equipment</h2><p>InHouse Wellness is a U.S. online retailer focused on home wellness equipment, including indoor and outdoor saunas, infrared saunas, cold plunges, float tanks and massage chairs. Its catalog includes equipment for residential wellness spaces as well as guidance around delivery, installation and product selection.</p><p>Visit <a href=https://inhousewellness.com/>https://inhousewellness.com/</a> to view the retailer's current catalog and policies.</p>"),("Editorial separation","<h2>Why this page is separate</h2><p>Health Research Database does not place product links inside claim reviews, topic dashboards, study records or Research Receipts. The commercial relationship is disclosed on the funding page so readers can evaluate it directly.</p>"),("Research is not a product claim","<h2>Evidence applies to protocols, not every device</h2><p>A study involving a particular sauna modality, temperature, wavelength, session duration or population should not be treated as proof that every retail product produces the same outcome. Check the intervention details and primary research before generalizing.</p>")]),
    }
    for rel,content in pages.items(): write(rel,content)
    for rel,target in {"latest/index.html":"/changes/","trials/index.html":"/trial-radar/","evidence/index.html":"/evidence-map/","sauna-longevity/index.html":"/claims/saunas-increase-longevity/","thermal-cycling-contrast-therapy/index.html":"/claims/contrast-therapy-improves-recovery/"}.items(): write(rel,redirect_page("/"+rel.replace("index.html",""),target))
    legacy={str(i):"/" for i in range(55)}
    legacy.update({"10-popular-foods-you-should-never-eat-over-30":"/healthspan/","10-surprising-scientific-insights-into-weight-loss-what-you-need-to-know":"/research/","10-ways-to-improve-intimacy-after-40-rekindle-the-spark":"/research/","21-ways-men-can-keep-having-kids-after-70-years-old-a-medical-perspective":"/research/","24-foods-to-avoid-to-reduce-cancer-risk":"/research/","25-positions":"/healthspan/","7-items-ed":"/research/","the-5-best-exercises-every-man-should-add-to-his-workout-plan":"/healthspan/","the-latest-scientific-breakthroughs-in-sauna-therapy":"/topics/sauna-heat-therapy/","the-top-5-saunas":"/resources/inhouse-wellness/","blood":"/claims/saunas-lower-blood-pressure/"})
    for old,target in legacy.items(): write(f"{old}/index.html",redirect_page(f"/{old}/",target))
    make_feeds(studies,trials,stats)
    static=["/","/claims/","/evidence-map/","/trial-radar/","/changes/","/research/","/data-download/","/methodology/","/claim-fidelity/","/about/","/editorial-policy/","/corrections/","/funding/","/data-sources/","/contact/","/resources/inhouse-wellness/","/healthspan/"]
    make_sitemaps(static,claims,topics,studies,trials,stats)
    write("llms.txt",f'''# Health Research Database\n\n> A continuously updated, transparent claim-to-evidence map of consumer health and wellness research.\n\nCanonical site: {BASE}/\nDataset edition: {iso_date(stats)}\nRefresh cadence: Monday and Thursday\nSources: PubMed and ClinicalTrials.gov\nLicense for normalized HRD metadata: CC BY 4.0\n\n## Primary products\n- Claim Ledger: {BASE}/claims/\n- Evidence Map: {BASE}/evidence-map/\n- Trial Radar: {BASE}/trial-radar/\n- Evidence Changes: {BASE}/changes/\n- Methodology: {BASE}/methodology/\n- Claim Fidelity framework: {BASE}/claim-fidelity/\n- Open data: {BASE}/data-download/\n- API status: {BASE}/api/v1/status.json\n\n## Citation guidance\nCite the individual claim page and its dataset edition. Research Receipts are reproducible counts within HRD's indexed snapshot, not systematic reviews or treatment recommendations. Claim Fidelity describes how directly evidence matches claim wording; it is not an efficacy score.\n\n## Crawling\nClaim answers, counts, dates, matched records and source links are present in initial HTML. No JavaScript execution is required to read core evidence.\n''')
    print(f'Built {len(claims)} claims, {len(topics)} topics, {len(studies)} studies and {len(trials)} trials')

if __name__=="__main__": main()
